apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: menu
  namespace: menu
spec:
  releaseName: menu
  chart:
    spec:
      chart: menu
      sourceRef:
        kind: HelmRepository
        name: menu
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    cache: redis-master.redis:6379
    ingress:
      enabled: true
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "nodeapp"
        dapr.io/app-port: "80"
        dapr.io/config: "tracing"
